name: emp_ai_auth
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  crypto: ^3.0.3
  dartz: ^0.10.1
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.10
  flutter_secure_storage: ^8.0.0
  freezed_annotation: ^2.4.1
  oauth2: ^2.0.2
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12

  rive: ^0.11.14
  timer_count_down: ^2.2.2
  envied: ^0.3.0+3
  pin_code_fields: ^8.0.1
  qr_flutter: ^4.1.0

  # EMP AI PACKAGES
  emp_ai_ds:
    path: ../emp_ai_ds
  responsive_framework: ^1.1.0
  webview_flutter: ^4.2.3
  flutter_inappwebview: ^6.0.0-beta.24+1
  universal_html: ^2.2.3
  go_router: ^10.1.2
  local_session_timeout: ^2.3.0
  another_flushbar: ^1.12.30
  widgets_to_image: ^0.0.2
  image_gallery_saver: ^2.0.3
  image_downloader_web: ^2.0.4
  get: ^4.6.5
  uuid: ^4.0.0
  unicons: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/svg/
    - assets/images/png/
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
