name: emp_ai_ds
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # json_theme: ^6.1.0
  google_fonts: ^5.1.0
  flex_seed_scheme: ^1.4.0
  flutter_svg: ^2.0.7
  flutter_riverpod: ^2.3.6
  responsive_grid: ^2.4.2
  side_sheet: ^1.0.4
  otp_text_field: ^1.1.3
  recase: ^4.1.0
  responsive_framework: ^1.1.0
  go_router: ^10.1.0
  adaptive_theme: ^3.3.0
  syncfusion_flutter_core: ^22.2.9
  tuple: ^2.0.2
  syncfusion_flutter_datagrid: ^22.2.9
  dartz: ^0.10.1
  file_picker: ^5.3.3
  jiffy: ^6.2.1
  flutter_switch: ^0.3.2
  get: ^4.6.5
  url_launcher: ^6.1.14
  js: ^0.6.7
  unicons: ^2.1.1
  storybook_flutter: ^0.14.0
  flutter_styled_toast: ^2.2.1
  another_flushbar: ^1.12.30
  

  emp_ai_auth:
    path: ../emp_ai_auth

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/svg/
    
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700 
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700 
    - family: Quicksand
      fonts:
        - asset: assets/fonts/quicksand/Quicksand-Light.ttf
          weight: 100
        - asset: assets/fonts/quicksand/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/quicksand/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/quicksand/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/quicksand/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/quicksand/Quicksand-Bold.ttf
          weight: 700 
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
